//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStock
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ingredientes
    {
        public int idIngrediente { get; set; }
        [Display(Name = "Nombre del Ingrediente")]
        public string nombre { get; set; }
        [Display(Name = "Descripción del Ingrediente")]
        public string descripcion { get; set; }
        [Display(Name = "Cantidad en Stock")]
        public int cantidad { get; set; }
        [Display(Name = "Fecha de Creación")]
        public System.DateTime fechaCreacion { get; set; }
    }
}
