//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStock
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Platillos
    {
        public int idPlatillo { get; set; }
        [Display(Name = "Nombre del Platillo")]
        public string nombre { get; set; }
        [Display(Name = "Descripción del Platillo")]
        public string descripcion { get; set; }
        [Display(Name = "Fecha de Creación")]
        public System.DateTime fechaCreacion { get; set; }
    }
}
